// Export pages
export '/pages/fristpage/fristpage_widget.dart' show FristpageWidget;
export '/pages/login_signup/login_signup_widget.dart' show LoginSignupWidget;
export '/pages/homepage/homepage_widget.dart' show HomepageWidget;
export '/chemistry/chemistrypage/chemistrypage_widget.dart'
    show ChemistrypageWidget;
export '/physics/physics_page/physics_page_widget.dart' show PhysicsPageWidget;
export '/math/math_page/math_page_widget.dart' show MathPageWidget;
export '/chemistry/chemistry1/chemistry1_widget.dart' show Chemistry1Widget;
export '/biology/biologypage/biologypage_widget.dart' show BiologypageWidget;
export '/physics/physics1/physics1_widget.dart' show Physics1Widget;
export '/math/math1/math1_widget.dart' show Math1Widget;
export '/biology/biology1/biology1_widget.dart' show Biology1Widget;
export '/pages/score/score_widget.dart' show ScoreWidget;
export '/physics/physics2/physics2_widget.dart' show Physics2Widget;
export '/physics/physics3/physics3_widget.dart' show Physics3Widget;
export '/physics/physics4/physics4_widget.dart' show Physics4Widget;
export '/physics/physics5/physics5_widget.dart' show Physics5Widget;
export '/physics/physics6/physics6_widget.dart' show Physics6Widget;
export '/physics/physics7/physics7_widget.dart' show Physics7Widget;
export '/physics/physics8/physics8_widget.dart' show Physics8Widget;
export '/physics/physics9/physics9_widget.dart' show Physics9Widget;
export '/physics/physics10/physics10_widget.dart' show Physics10Widget;
export '/math/math2/math2_widget.dart' show Math2Widget;
export '/math/math3/math3_widget.dart' show Math3Widget;
export '/math/math4/math4_widget.dart' show Math4Widget;
export '/math/math5/math5_widget.dart' show Math5Widget;
export '/math/math6/math6_widget.dart' show Math6Widget;
export '/math/math7/math7_widget.dart' show Math7Widget;
export '/math/math8/math8_widget.dart' show Math8Widget;
export '/math/math9/math9_widget.dart' show Math9Widget;
export '/math/math10/math10_widget.dart' show Math10Widget;
export '/math/math11/math11_widget.dart' show Math11Widget;
export '/math/math12/math12_widget.dart' show Math12Widget;
export '/math/math13/math13_widget.dart' show Math13Widget;
export '/math/math14/math14_widget.dart' show Math14Widget;
export '/math/math15/math15_widget.dart' show Math15Widget;
export '/math/math16/math16_widget.dart' show Math16Widget;
export '/math/math17/math17_widget.dart' show Math17Widget;
export '/chemistry/chemistry2/chemistry2_widget.dart' show Chemistry2Widget;
export '/chemistry/chemistry3/chemistry3_widget.dart' show Chemistry3Widget;
export '/chemistry/chemistry4/chemistry4_widget.dart' show Chemistry4Widget;
export '/chemistry/chemistry5/chemistry5_widget.dart' show Chemistry5Widget;
export '/chemistry/chemistry6/chemistry6_widget.dart' show Chemistry6Widget;
export '/chemistry/chemistry7/chemistry7_widget.dart' show Chemistry7Widget;
export '/chemistry/chemistry8/chemistry8_widget.dart' show Chemistry8Widget;
export '/chemistry/chemistry9/chemistry9_widget.dart' show Chemistry9Widget;
export '/chemistry/chemistry10/chemistry10_widget.dart' show Chemistry10Widget;
export '/chemistry/chemistry11/chemistry11_widget.dart' show Chemistry11Widget;
export '/biology/biology2/biology2_widget.dart' show Biology2Widget;
export '/biology/biology3/biology3_widget.dart' show Biology3Widget;
export '/biology/biology4/biology4_widget.dart' show Biology4Widget;
export '/biology/biology5/biology5_widget.dart' show Biology5Widget;
export '/biology/biology6/biology6_widget.dart' show Biology6Widget;
export '/biology/biology7/biology7_widget.dart' show Biology7Widget;
export '/biology/biology8/biology8_widget.dart' show Biology8Widget;
export '/biology/biology9/biology9_widget.dart' show Biology9Widget;
export '/biology/biology10/biology10_widget.dart' show Biology10Widget;
export '/biology/biology11/biology11_widget.dart' show Biology11Widget;
export '/settings/settings_page/settings_page_widget.dart'
    show SettingsPageWidget;
export '/settings/playing_policy/playing_policy_widget.dart'
    show PlayingPolicyWidget;
export '/settings/contact_us/contact_us_widget.dart' show ContactUsWidget;
export '/settings/who_are_we/who_are_we_widget.dart' show WhoAreWeWidget;
